server:
  port: 8081

spring:
  main:
    banner-mode: "off"

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io.neo9.ingress.access: DEBUG
    #io.javaoperatorsdk.operator: WARN

javaoperatorsdk:
  controllers:
    visitorgroupcontroller:
      retry:
        maxAttempts: 3

extension:
  # will also scan ingress annotations to find operator activations label
  # It's clearly not the best way to detect concerned ingresses (scan all cluster ingresses),
  # and does not takes advantages of kubernetes API (label filtering) ;
  # BUT it provide an easier integration with tools that generate ingress
  watchIngressAnnotations:
    enabled: false

  updateIstioIngressSidecar:
    enabled: false
    ingressNamespace: nginx-istio-ingress
    additionalEgressRulesEntries:
      - "istio-system"
