server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io.neo9.kubernetesmutationoperator: DEBUG

javaoperatorsdk:
  controllers:
    visitorgroupcontroller:
      retry:
        maxAttempts: 3
