server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io.neo9.gatekeeper: DEBUG
    #io.javaoperatorsdk.operator: WARN

javaoperatorsdk:
  controllers:
    visitorgroupcontroller:
      retry:
        maxAttempts: 3
